Repository chill-viking/npm-ci, pull requests merged in 2023-02, with the labels that each got.

#4 chore(main): release 1.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#12 chore(lint): ignore compare links
  .github/workflows/test-action.yml
  .markdown-link-check.json
  .mega-linter.yml
  .yamllint.yml
Labels: non-functional improvement :tada:

#9 chore(main): release 1.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#13 fix(action): add branding
  action.yml
Labels: bug :bug:

#14 chore(main): release 1.1.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#17 feat(action): add output `restored_from_cache`
  .github/workflows/run-action.yml
  .github/workflows/test-action.yml
  README.md
  action.yml
Labels: bug :bug:, enhancement :bulb:

#18 chore(main): release 1.2.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
